name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bootstrap-setup
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn workspace @terra-ping/universal-model typecheck
      - run: yarn workspace @terra-ping/transformers typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bootstrap-setup
        with:
          node-version: '20'
          cache: 'yarn'

      - run: yarn workspace @terra-ping/web build
